# Generated by Django 5.0.6 on 2026-05-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
