# Generated by Django 6.0.5 on 2026-05-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_student_image_student_pdf_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
