# Generated by Django 6.0.5 on 2026-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
