# Generated by Django 5.0.6 on 2026-05-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
