# Generated by Django 5.0.6 on 2026-05-28 10:52

import coreapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[coreapp.models.validate_image]),
        ),
        migrations.AlterField(
            model_name='student',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/', validators=[coreapp.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='student',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[coreapp.models.validate_video]),
        ),
    ]
