# Generated by Django 5.0.6 on 2026-05-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_alter_student_image_alter_student_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB_AD',
            field=models.DateField(blank=True, null=True),
        ),
    ]
