# Generated by Django 5.0.6 on 2026-05-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_student_dob_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='DOB_AD',
        ),
        migrations.AddField(
            model_name='student',
            name='DOB_BS',
            field=models.CharField(default='', max_length=20),
        ),
    ]
