# Generated by Django 5.0.6 on 2026-05-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_remove_student_dob_remove_student_dob_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB_BS',
        ),
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
