# Generated by Django 5.0.6 on 2026-05-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_alter_student_dob_alter_student_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_date', models.CharField(max_length=20)),
                ('ad_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
