# Generated by Django 5.0.6 on 2026-05-31 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_delete_event_alter_student_dob_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
