# Generated by Django 5.0.6 on 2026-06-01 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0017_rename_dob_student_dob_ad_student_dob_bs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dob_ad',
            new_name='DOB',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob_bs',
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
