# Generated by Django 5.0.6 on 2026-06-02 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_rename_dob_ad_student_dob_remove_student_dob_bs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10-digit number')]),
        ),
    ]
